# Generated by Django 4.2.2 on 2023-06-23 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_post_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='price',
        ),
    ]
